config/routes.rb
Rails.application.routes.draw do
 
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "posts#index"
  get "/about", to: "posts#about"
  resources :articles
  get 'signup', to: 'users#new'
  #form looks for users path to submit form when completed, so we need this:
  #post 'users', to: 'users#create'
  #or I can get all the routes set up automatically (except the signup one I already have): 
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  # has_rich_text :description
  validates :title, presence: true, length: {minimum: 6, maximum: 100}
  validates :description, presence: true, length: {minimum: 10, maximum: 500}
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article 
  belongs_to :category 
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, length: {minimum:3, maximum:25}
  validates_uniqueness_of :name #ensures we dont have duplicate names
  has_many :article_categories
  has_many :articles, through: :article_categories
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email = email.downcase }
    has_many :articles, dependent: :destroy
    validates :username, presence: true, 
                         uniqueness: { case_sensitive: false }, 
                         length: { minimum: 3, maximum: 25 }
    VALID_EMAIL_REGEX = /\A([\w+\-]\.?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
    validates :email, presence: true, 
                      uniqueness: { case_sensitive: false }, 
                      length: { maximum: 105 },
                      format: {with: VALID_EMAIL_REGEX}
    has_secure_password
end


 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?
  def current_user
    #from the sessions controller we grab the user id: session[:user_id]
    @current_user ||= User.find(session[:user_id]) if session[:user_id]  
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:alert] = "You must be logged in to perform that action"
      redirect_to login_path
    else
      puts "User is logged in." # Add this line
    end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]

    def index
        @articles = Article.paginate(:page => params[:page], :per_page => 5)

    end

    def show
    end

    def new
      @article = Article.new
    end

    def edit
     # binding.break this is the debugger
    end

    def create

      @article = Article.new(article_params)
      @article.user = current_user #use current_user method instead of hard coding
      if @article.save
        flash[:notice] = "Your article was successfully created!"
        redirect_to @article
      else
        render 'new'
      end
    end

    def update
      if @article.update(article_params)
        flash[:notice] = "Your article was successfully updated"
        redirect_to @article
      else
        render :edit, status: :unprocessable_entity
      end

    end

    def destroy
      @article.destroy
      redirect_to articles_path, notice: 'Article was successfully destroyed.'
    end


    private

    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :description, category_ids: [])
    end

    def require_same_user
      if current_user != @article.user && !current_user.admin?
        flash[:alert] = "You can only edit or delete your own articles"
        redirect_to @article
      end
    end



end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :require_admin, except: [:index, :show]

    def new
        @category = Category.new
    end

    def create
        @category = Category.new(category_params)
        if @category.save
            flash[:notice] = "Category was successfully created"
            redirect_to @category
        else       
            render 'new'
        end
    end

    def edit
        @category = Category.find(params[:id])
    end

    def update
        @category = Category.find(params[:id])
        if @category.update(category_params)
            flash[:notice] = "Category name updated successfully"
            redirect_to  @category
        else 
            render 'edit'
        end
    end

    def index
       @categories = Category.paginate(:page => params[:page], :per_page => 5 )
    end

    def show
        @category = Category.find(params[:id])
        @articles = @category.articles.paginate(:page => params[:page], :per_page => 5)
    end

    
    private

    def category_params
      params.require(:category).permit(:name)
    end
  
    def require_admin
       if !(logged_in? && current_user.admin?)
        flash[:alert] = "Only admins can perform this action"
        redirect_to categories_path
        end
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController    
    def index
      redirect_to articles_path if logged_in?           
    end

    def about        
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
        
    end

    def create
        user = User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
          session[:user_id] = user.id #this will allow logged in users to authenticate once and remian signed in for future requests
          flash[:notice] = "Log in successful"
          redirect_to user
        else 
          flash.now[:alert]="There was something wrong with your login credentials"  
          render 'new'      
        end
    end

    def destroy
        session[:user_id] = nil
        flash[:notice] = "Logged out"
        redirect_to root_path
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_user, only: [:edit, :update]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  
  def show
    @articles = @user.articles.paginate(:page => params[:page], :per_page => 5)
  end

  def index
    @users = User.paginate(:page => params[:page], :per_page => 5)

  end

  def new
    @user = User.new
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "Your account information has been updated"
      redirect_to @user 
    else       
      render 'edit'
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
        session[:user_id] = @user.id
        flash[:notice] = "Welcome to Freya's Blog #{@user.username}, you have successfully signed up."
        redirect_to  articles_path
    else       
        render 'new'
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil if @user == current_user #to prevent session's user id to be set to the id of a deleted user we set it to nil, to avoid admin being logged out, we added if.
    flash[:notice] = "Account and all associated articles successfully deleted"
    redirect_to users_path
  end

  def admin?
    self.admin
  end
  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])

  end
  
  def require_same_user
    if current_user != @user && !current_user.admin?
      flash[:alert] = "You can only edit or delete your own account"
      redirect_to @user
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user, options = { size: 80 })
    email_address = user.email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    size = options[:size]
    gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(gravatar_url, alt:user.username, class: "rounded shadow mx-auto d-block")
  end 

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/articles/_article.html.erb
<div class="container">
    <% @articles.each do |article| %>
      <div class="row justify-content-md-center">
        <div class="col-8">
          <div class="card text-center mt-4 shadow rounded">
            <div class="card-header fst-italic">
              <% if article.user %>
                Author: <%= link_to article.user.username, user_path(article.user)  %>
              <% end %>
              <% if article.categories.any? %>
                <div class="mt-2"><%= render article.categories %></div>
              <% end %>
            </div>
            <div class="card-body">
              <h5 class="card-title"><td><%= link_to article.title, article_path(article), class:"title-text" %></td></h5>
              <p class="card-text"><td><%= truncate(article.description, length:75)%></td></p>
              <%= link_to 'View', article_path(article), class:"btn btn-sm btn-outline-secondary" %>
              
              <% if logged_in? && (article.user == current_user || current_user.admin?) %>
                <%= link_to 'Edit', edit_article_path(article), class:"btn btn-sm btn-outline-success" %>
                <%= link_to 'Delete', article_path(article), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class:"btn btn-sm btn-outline-danger" %>
              <% end %>
            
            </div>
            <div class="card-footer text-body-secondary text-center card-text">
              <small>
                Created <%= time_ago_in_words(article.created_at) %> ago,
                edited <%= time_ago_in_words(article.updated_at) %> ago
              </small>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>

app/views/articles/_form.html.erb
<div class="container">
    <div class="row justify-content-center">
        <%= render 'shared/errors', obj: @article %>
        <div class="col-10">
            
            <%= form_with(model: @article,local: true, data: { turbo: false }) do |f| %>
                <div class="row form-group">
                    <%= f.label :title, class:"col-2 col-form-label form-label-text fw-bold" %>
                    <div class="col-10">
                        <%= f.text_field :title, class:"form-control shadow", placeholder:"Article title" %>
                    </div>
                </div>

                <div class="row form-group">
                    <%= f.label :description, class:"col-2 col-form-label form-label-text fw-bold" %><br>
                    <div class="col-10 mb-4">
                        <%= f.text_area :description, rows:10, class:"form-control mt-3 shadow",placeholder:"Article description" %>
                    </div>                    
                </div>

                <div class="row form-group">
                    <%= f.label :category_ids, class: "col-2 col-form-label form-label-text fw-bold" %><br>
                    <div class="col-10">
                      <%= f.collection_select :category_ids, Category.all, :id, :name, 
                      { prompt: "Please select your categories (this sectionc an be empty)"}, {multiple: true, size: 5, class: "custom-select, form-control shadow" } %>
                    </div>
                  </div>
                        <%= f.submit class:"btn btn-article btn-lg mt-3" %>
                        <%= link_to 'Back to Articles List', articles_path, class: "btn btn-article btn-lg mt-3" %>
            </div>
        </div>
        <% end %>

    </div>
</div>

app/views/articles/edit.html.erb
<div class="container mt-5 text-center">
    <h2>Edit article</h2>
    <%= render 'form' %>
</div>

app/views/articles/index.html.erb
<div class="container">
<h2 class="text-center mt-5">Articles</h2>

<div class="flickr_pagination">
    <%= will_paginate @articles, :container => false %>
</div>

<%= render 'article' %>

<div class="flickr_pagination mb-5">
    <%= will_paginate @articles, :container => false %>
</div>

</div>

app/views/articles/new.html.erb
<div class="container mt-5 text-center">

    <h2>Create a new article</h2>

    <%= render 'form' %>

</div>

app/views/articles/show.html.erb
<h2 class="text-center mt-5"><%= @article.title %></h2>
<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-8">
      <div class="card text-center mt-4 shadow rounded">
        <div class="card-header fst-italic">
          Author: <%= @article.user.username if @article.user %>
          <%= link_to gravatar_for(@article.user), user_path(@article.user) %>
          <% if @article.categories.any? %>
          <div class="mt-2"><%= render @article.categories %></div>
        <% end %>
        </div>
        <div class="card-body">
          <div class="card-text text-start"><td><%= simple_format(@article.description) %></td></div>
          
          <% if logged_in? && (@article.user == current_user || current_user.admin?) %>
          <%= link_to 'Edit', edit_article_path(@article), class:"btn btn-sm btn-outline-success" %>
          <%= link_to 'Delete', article_path(@article), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class:"btn btn-sm btn-outline-danger" %>
          <% end %>

          <%= link_to 'Back to Articles List', articles_path, class:"btn btn-sm btn-outline-secondary" %>
        </div>
        <div class="card-footer text-body-secondary text-center card-text">
          <small>
            Created <%= time_ago_in_words(@article.created_at) %> ago,
            edited <%= time_ago_in_words(@article.updated_at) %> ago
          </small>
        </div>
      </div>
    </div>
  </div>


</div>

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category), class:"badge badge-pill bg-pill mx-1" %>

app/views/categories/_form.html.erb
<div class="container">

    <%= form_with(model: @category, local: true) do |form| %>
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
    
    <%= form.submit 'Done', class: 'btn btn-outline-dark mt-2' %>
    <% end %>

</div>

app/views/categories/edit.html.erb
<% if @category.errors.any? %>
  <div class="row justify-content-center">
    <div class="col-10">
      <div class="alert alert-danger text-center alert-dismissible fade show" role="alert">
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        <h4 class="alert-heading">The following errors prevented the category from saving:</h4>
        <% @category.errors.full_messages.each do |msg| %>
          <p><%= msg %></p>
        <% end %>
      </div>
    </div>
  </div>
<% end %>
<div class="container mt-5">
    <h2>Edit Category</h2>
    <%= render 'form' %>
</div>
<div class="mb-3 text-center">
    <%= link_to '[Cancel and return to Category]', category_path(@category), class:'text-secondary' %>
</div>

app/views/categories/index.html.erb
<h2 class="text-center mt-5">Categories</h2>

<div class="flickr_pagination">
    <%= will_paginate @categories, :container => false %>
</div>

<div class="container">
    <% @categories.each do |category| %>
      <div class="row justify-content-md-center">
        <div class="col-4 mt-4">
          <div class="card text-center mt-4 shadow rounded">
            
            <div class="card-body">
              <h5 class="card-title"><td><%= link_to category.name, category_path(category), class:"title-text" %></td></h5>            
              <p class="card-text"><%= pluralize(category.articles.count, "article") %></p>
            </div>
            <div class="card-footer text-body-secondary text-center card-text">
              <small>
                Created <%= time_ago_in_words(category.created_at) %> ago,
                edited <%= time_ago_in_words(category.updated_at) %> ago
              </small>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>

<div class="flickr_pagination">
    <%= will_paginate @categories, :container => false %>
</div>

app/views/categories/new.html.erb
<% if @category.errors.any? %>
  <div class="row justify-content-center">
    <div class="col-10">
      <div class="alert alert-danger text-center alert-dismissible fade show" role="alert">
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        <h4 class="alert-heading">The following errors prevented the category from saving:</h4>
        <% @category.errors.full_messages.each do |msg| %>
          <p><%= msg %></p>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

<div class="container mt-5">
  <h2>Create New Category</h2>
  <%= render 'form' %>
</div>

<div class="mb-3 text-center">
  <%= link_to '[Cancel and return to Categories list]', categories_path, class:'text-secondary' %>
</div>

app/views/categories/show.html.erb
<div class="container text-center mt-5 p-3">

<h2 class="mb-3">Category: <%= @category.name %></h2>

<% if logged_in?  && current_user.admin?%>
    <div class="text-center mt-4">
        <%= link_to "Edit category name", edit_category_path(@category), class:"btn btn-sm btn-outline-secondary" %>
    </div>
<% end %>
   

    <h3 class="mt-5">Articles</h3>

    <div class="flickr_pagination">
        <%= will_paginate @articles, :container => false %>
    </div>

    <%= render 'articles/article' %>

    <div class="flickr_pagination mb-4">
        <%= will_paginate @articles, :container => false %>
    </div>


</div>

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-4 bg-dark text-white-50 fixed-bottom mt-5">
    <div class="container text-center ">
        <small>Copyright &copy; <%= link_to "Marilyn Marquez", class:"footer-text" %></small>
    </div>
</footer>

app/views/layouts/_messages.html.erb
<% flash.each do |name, message| %>
<div class="alert alert-success alert-<%= name== 'notice' ? 'success' : 'danger' %> fade show" role="alert">
<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
<%= message %>
<% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary navbar-dark">
    <div class="container-fluid">
      <%= link_to "Freya's Blog", root_path, class:"navbar-brand", id:"logo"  %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <%= link_to 'Bloggers', users_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Articles
            </a>
            <ul class="dropdown-menu">
              <% if logged_in? %>
                <%= link_to "Create new article", new_article_path, class:'dropdown-item' %>
              <% end %>
              <%= link_to "View Articles", articles_path, class:'dropdown-item'  %>
              <li><hr class="dropdown-divider"></li>
              
              <li><a class="dropdown-item" href="#">Something else here</a></li>
            </ul>
          </li>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Categories
            </a>
            <ul class="dropdown-menu">
              <% if logged_in? && current_user.admin? %>
                <%= link_to "Create new category", new_category_path, class:'dropdown-item' %>
              <% end %>
              <%= link_to "View Categories", categories_path, class:'dropdown-item'  %>

            </ul>
          </li>

          <% if logged_in? %>

            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                <%= "(Admin)" if current_user.admin? %> <%= current_user.username %>
              </a>
              <ul class="dropdown-menu">  
                <%= link_to "View Your Profile", user_path(current_user), class:'dropdown-item' %>
                <%= link_to "Edit Your Profile", edit_user_path(current_user), class:'dropdown-item' %>
                <%= link_to "Delete Profile", user_path(current_user), class:'dropdown-item text-danger', data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>  
              </ul>
            </li>

            <li class="nav-item">
              <%= link_to 'Logout', logout_path, class:"nav-link",  data: { turbo_method: :delete } %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to 'Login', login_path, class:"nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to 'Sign up', signup_path, class:"nav-link" %>
            </li>
          <% end %>
        
        </ul>
        <form class="d-flex" role="search">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Freya's Blog</title>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag 'custom', media: 'all' %> <!-- Add this line for custom css -->
    <%= javascript_include_tag 'application', 'data-turbo-track': 'reload' %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="d-flex flex-column">
    <%= render 'layouts/navigation' %>
    <div id="page-content">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>

</html>

app/views/posts/about.html.erb
<h1>About me...</h1>
<p>This is the about page for my ruby blog</p>


<%= link_to 'Articles List', articles_path %>
<%= link_to 'Home Page', root_path %>

app/views/posts/index.html.erb
<div class="container" id="home-container">    
  <div class="page-content">
    <div class="hero custom-hero p-5 text-center shadow-lg rounded shadow-lg">
        <br><br><br><br><br><br><br>
        <h1 class="display-4 hero-text">Welcome To Freya's Blog!</h1>
        <p class="lead">This is a simple hero unit</p>
        <p>It uses utility classes for whatever....</p>
        <%= link_to "Sign up!", signup_path, class: "btn btn-light btn-lg mb-5 mx-5 btn-text" %>
    </div>
  </div>  
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row justify-content-center">
    <div class="col-10">
      <div class="alert alert-danger text-center alert-dismissible fade show" role="alert">
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        <h4 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase %> from saving:</h4>
        <% obj.errors.full_messages.each do |msg| %>
        <p><%= msg %></p>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/users/_form.html.erb
<div class="container">
    <div class="row justify-content-center">
        <%= render 'shared/errors', obj: @user %>
        <div class="col-10">
            
            <%= form_with(model: @user,local: true, data: { turbo: false }) do |f| %>
                <div class="row form-group">
                    <%= f.label :username, class:"col-2 col-form-label form-label-text fw-bold" %>
                    <div class="col-10">
                        <%= f.text_field :username, class:"form-control shadow", placeholder:"Enter your username" %>
                    </div>

                </div>

                <div class="row form-group">
                        <%= f.label :email, class:"col-2 col-form-label form-label-text fw-bold" %><br>
                        <div class="col-10">
                            <%= f.email_field :email, class:"form-control mt-3 shadow",placeholder:"Enter your email address" %>
                        </div>
                    
                </div>

                <div class="row form-group">
                    <%= f.label :password, class:"col-2 col-form-label form-label-text fw-bold" %><br>
                    <div class="col-10">
                        <%= f.password_field :password, class:"form-control mt-3 shadow",placeholder:"Choose a password" %>
                    </div>
                
                </div>

                        <%= f.submit(@user.persisted? ? 'Update Account' : "Sign Up", class:"btn btn-article btn-lg mt-3") %>
                        
            </div>
        </div>
        <% end %>

    </div>
</div>

app/views/users/edit.html.erb
<div class="container mt-5 text-center">

    <h2>Edit Your User Profile</h2>

    <%= render 'form' %>

</div>

app/views/users/index.html.erb
<div class="container mt-5 text-center">

<h2>Freya's Bloggers</h2>
    <div class="flickr_pagination">
        <%= will_paginate @users, :container => false %>
    </div>
  
    <div class="container">
        <% @users.each do |user| %>
        <div class="row justify-content-md-center">
            <div class="col-8">
            <div class="card text-center mt-4 shadow rounded">
                <div class="card-header fst-italic">
                Author: <%= link_to user.username, user_path(user) %>
                </div>
                <div class="card-body">
                <h5 class="card-title">
                    <%= link_to gravatar_for(user, size:150), user %>
                </h5>
                <p class="card-text"><td><%= pluralize(user.articles.count, "article") %></td></p>
                <%= link_to 'View Profile', user, class:"btn btn-sm btn-outline-secondary" %>
                
                <% if logged_in? %>
                  <% if user == current_user %>
                    <%= link_to 'Edit Profile', edit_user_path(user), class:"btn btn-sm btn-outline-success" %>
                  <% end %> 
                  <% if current_user.admin? %> 
                    <%= link_to "Delete User", user_path(user), class: "btn btn-sm btn-outline-danger", data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
                  <% end %>
                <% end %>
                </div>
                <div class="card-footer text-body-secondary text-center card-text">
                <small>
                    Joined <%= time_ago_in_words(user.created_at) %> ago
                    
                </small>
                </div>
            </div>
            </div>
        </div>
        <% end %>
    </div>
    <div class="flickr_pagination mb-4">
        <%= will_paginate @users, :container => false %>
    </div>

    </div>

app/views/users/new.html.erb
<div class="container mt-5 text-center">

    <h2>Sign up for Freya's Blog</h2>

    <%= render 'form' %>

</div>

<br><br><br><br><br><br><br><br><br><br><br><br><br><br>

app/views/users/show.html.erb
<div class="container mt-5 text-center">

    <h2 class="mb-3"><%= @user.username %>'s Profile</h2>

    <%= gravatar_for @user, size: 200 %>

    <% if logged_in? %>
    
      <% if @user == current_user %>
        <div class="text-center mt-4">
            <%= link_to "Edit your Profile", edit_user_path(@user), class:"btn btn-sm btn-outline-secondary" %>
        </div>
      <% end %>
      <% if current_user.admin? %> 
        <div class="text-center m-4">
          <%= link_to "Delete User", user_path(@user), class: "btn btn-outline-danger", data: {turbo_method: :delete, turbo_confirm: "Are you sure you want to delete the user account and all associated articles?"} %>
        </div>
        <% end %>
    <% end %>

    <h3 class="mt-5"><%= @user.username %>'s Articles</h3>

    <div class="flickr_pagination">
        <%= will_paginate @articles, :container => false %>
    </div>

    <%= render 'articles/article' %>

    <div class="flickr_pagination mb-4">
        <%= will_paginate @articles, :container => false %>
    </div>

</div>